# Generated by Django 5.1.7 on 2025-03-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('STDNT', 'Student'), ('TCHR', 'Teacher'), ('ADMIN', 'Administrator')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
