# Generated by Django 5.1.7 on 2025-05-20 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='begins_at',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='ends_at',
        ),
        migrations.AddField(
            model_name='schedules',
            name='begins_at_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='schedules',
            name='begins_at_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='ends_at_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='schedules',
            name='ends_at_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
