# Generated by Django 5.1.7 on 2025-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_remove_schedules_begins_at_remove_schedules_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='begins_at_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='begins_at_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='ends_at_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='ends_at_time',
            field=models.TimeField(),
        ),
    ]
